"""Export Utilities for Lexigraph

Provides functionality to export summaries and reports in various formats.
"""

from typing import Dict, List, Any, Optional
from datetime import datetime
import json


def export_to_markdown(
    content: str,
    title: str = "Lexigraph Export",
    include_header: bool = True
) -> str:
    """
    Format content as a downloadable Markdown document.
    
    Args:
        content: The main content to export
        title: Document title
        include_header: Whether to include metadata header
        
    Returns:
        Formatted Markdown string
    """
    lines = []
    
    if include_header:
        lines.append("---")
        lines.append(f"title: {title}")
        lines.append(f"generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        lines.append("generator: Lexigraph")
        lines.append("---")
        lines.append("")
    
    lines.append(f"# {title}")
    lines.append("")
    lines.append(content)
    
    return "\n".join(lines)


def export_meeting_summary(
    extraction: Any,  # MeetingExtraction
    include_raw_data: bool = False
) -> str:
    """
    Export meeting extraction as formatted Markdown.
    
    Args:
        extraction: MeetingExtraction object
        include_raw_data: Whether to include raw JSON data
        
    Returns:
        Formatted Markdown string
    """
    lines = []
    
    # Header
    lines.append(f"# {extraction.meeting_title or 'Meeting Summary'}")
    if extraction.meeting_date:
        lines.append(f"*Date: {extraction.meeting_date}*")
    lines.append("")
    
    # People
    if extraction.people:
        lines.append("## 👥 Attendees")
        for person in extraction.people:
            role = f" ({person.role})" if person.role else ""
            lines.append(f"- **{person.name}**{role}")
        lines.append("")
    
    # Topics
    if extraction.topics:
        lines.append("## 💬 Topics Discussed")
        for topic in extraction.topics:
            desc = f": {topic.description}" if topic.description else ""
            lines.append(f"- **{topic.name}**{desc}")
        lines.append("")
    
    # Decisions
    if extraction.decisions:
        lines.append("## ✅ Decisions Made")
        for decision in extraction.decisions:
            by = f" *(by {decision.made_by})*" if decision.made_by else ""
            lines.append(f"- {decision.description}{by}")
        lines.append("")
    
    # Action Items
    if extraction.action_items:
        lines.append("## 📋 Action Items")
        lines.append("")
        lines.append("| Task | Owner | Deadline | Priority |")
        lines.append("|------|-------|----------|----------|")
        for action in extraction.action_items:
            owner = action.owner or "TBD"
            deadline = action.deadline or "-"
            priority = action.priority or "-"
            lines.append(f"| {action.description} | {owner} | {deadline} | {priority} |")
        lines.append("")
    
    # Commitments
    if extraction.commitments:
        lines.append("## 🤝 Commitments")
        for commitment in extraction.commitments:
            lines.append(f"- **{commitment.made_by}**: {commitment.description}")
        lines.append("")
    
    # Footer
    lines.append("---")
    lines.append(f"*Generated by Lexigraph on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    
    return "\n".join(lines)


def export_action_items(deadlines: Dict[str, List[Dict]]) -> str:
    """
    Export deadline tracker data as Markdown.
    
    Args:
        deadlines: Dict with 'overdue', 'due_soon', 'upcoming', 'no_deadline' lists
        
    Returns:
        Formatted Markdown string
    """
    lines = []
    
    lines.append("# 📋 Action Items Report")
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    lines.append("")
    
    # Overdue
    if deadlines.get("overdue"):
        lines.append("## 🔴 Overdue")
        for item in deadlines["overdue"]:
            owner = item.get("owner", "Unassigned")
            lines.append(f"- **{item['task']}** ({owner}) - Due: {item['deadline']}")
        lines.append("")
    
    # Due Soon
    if deadlines.get("due_soon"):
        lines.append("## 🟡 Due Soon")
        for item in deadlines["due_soon"]:
            owner = item.get("owner", "Unassigned")
            lines.append(f"- **{item['task']}** ({owner}) - Due: {item['deadline']}")
        lines.append("")
    
    # Upcoming
    if deadlines.get("upcoming"):
        lines.append("## 🟢 Upcoming")
        for item in deadlines["upcoming"]:
            owner = item.get("owner", "Unassigned")
            deadline = item.get("deadline", "No deadline")
            lines.append(f"- **{item['task']}** ({owner}) - Due: {deadline}")
        lines.append("")
    
    # No Deadline
    if deadlines.get("no_deadline"):
        lines.append("## ⚪ No Deadline Set")
        for item in deadlines["no_deadline"]:
            owner = item.get("owner", "Unassigned")
            lines.append(f"- {item['task']} ({owner})")
        lines.append("")
    
    lines.append("---")
    lines.append("*Export from Lexigraph*")
    
    return "\n".join(lines)


def export_insights_report(
    person_insights: List[Dict],
    topic_trends: List[Dict]
) -> str:
    """
    Export cross-meeting insights as Markdown.
    
    Args:
        person_insights: List of person analytics
        topic_trends: List of topic analytics
        
    Returns:
        Formatted Markdown string
    """
    lines = []
    
    lines.append("# 📊 Cross-Meeting Insights Report")
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    lines.append("")
    
    # Person Insights
    lines.append("## 👥 Team Engagement")
    lines.append("")
    lines.append("| Name | Role | Meetings | Actions | Decisions | Commitments |")
    lines.append("|------|------|----------|---------|-----------|-------------|")
    
    for person in person_insights:
        name = person.get("name", "Unknown")
        role = person.get("role", "-")
        meetings = person.get("meetings_attended", 0)
        actions = person.get("action_items", 0)
        decisions = person.get("decisions_made", 0)
        commits = person.get("commitments", 0)
        lines.append(f"| {name} | {role} | {meetings} | {actions} | {decisions} | {commits} |")
    
    lines.append("")
    
    # Topic Trends
    lines.append("## 💬 Topic Trends")
    lines.append("")
    
    for topic in topic_trends:
        name = topic.get("topic", "Unknown")
        count = topic.get("meeting_count", 0)
        desc = topic.get("description", "")
        lines.append(f"### {name} ({count} meetings)")
        if desc:
            lines.append(f"*{desc}*")
        lines.append("")
    
    lines.append("---")
    lines.append("*Export from Lexigraph*")
    
    return "\n".join(lines)


def create_download_button_data(content: str, filename: str) -> Dict[str, str]:
    """
    Prepare data for Streamlit download button.
    
    Args:
        content: The content to download
        filename: The filename for download
        
    Returns:
        Dict with 'data', 'filename', and 'mime'
    """
    return {
        "data": content,
        "filename": filename,
        "mime": "text/markdown"
    }
